apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    type: frountend
    client: ibm
spec:
  containers:
  - name: webapp-cont1
    image: nginx:1.19
    ports:
    - containerPort: 80
  - name: ubuntu-cont
    image: ubuntu:22.04
    command: ["/bin/bash", "-c", "sleep infinity"]
    tty: true
    stdin: true

