FROM ubuntu:20.04

LABEL maintainer="Kadali <kadali@example.com>" \
      description="Example showing WORKDIR usage"

# Set working directory
WORKDIR /app

# Copy files into /app
COPY . .

# Run commands inside /app
RUN echo "Hello from WORKDIR" > message.txt

CMD ["cat", "message.txt"]

