# Start with a base image
FROM ubuntu:20.04

# Add metadata about the image
LABEL maintainer="Kadali <kadali@example.com>"
LABEL version="1.0"
LABEL description="This image sets up a basic Ubuntu environment with curl installed."

